---
colors:
  um_maize:
    color:    "#FFCB05"
    contrast: "grey_1"
  um_blue:
    color:    "#00274C"
    contrast: "white"

  black:
    color:    "#000000"
    contrast: "grey_7"
  white:
    color:    "#FFFFFF"
    contrast: "grey_1"

  grey_1:
    color:    "#333333"
    contrast: "white"
  grey_2:
    color:    "#4E4E4E"
    contrast: "white"
  grey_3:
    color:    "#6E6E6E"
    contrast: "white"
  grey_4:
    color:    "#CCCCCC"
    contrast: "grey_1"
  grey_5:
    color:    "#E5E5E5"
    contrast: "grey_1"
  grey_6:
    color:    "#F2F2F2"
    contrast: "grey_1"
  grey_7:
    color:    "#FAFAFA"
    contrast: "grey_1"

  main_1:
    color:    "#00274C"
    contrast: "white"
  main_2:
    color:    "#0C5292"
    contrast: "white"
  main_3:
    color:    "#126DC1"
    contrast: "white"
  main_4:
    color:    "#CCE6FF"
    contrast: "main_1"
  main_5:
    color:    "#E6F3FF"
    contrast: "main_1"
  main_6:
    color:    "#F2F9FF"
    contrast: "main_1"

  green_1:
    color:    "#057C42"
    contrast: "white"
  green_2:
    color:    "#05A657"
    contrast: "black"
  green_3:
    color:    "#E2F4EB"
    contrast: "green_1"

  red_1:
    color:    "#C53B26"
    contrast: "white"
  red_2:
    color:    "#ED5D47"
    contrast: "black"
  red_3:
    color:    "#FFEAE7"
    contrast: "red_1"

  orange_1:
    color:    "#AA6500"
    contrast: "white"
  orange_2:
    color:    "#E77504"
    contrast: "black"
  orange_3:
    color:    "#FFEEDD"
    contrast: "orange_1"

  teal_1:
    color:    "#10788E"
    contrast: "white"
  teal_2:
    color:    "#14A2BF"
    contrast: "black"
  teal_3:
    color:    "#E4F3F8"
    contrast: "teal_1"

scss_variables:
  fa_icon_root:
    "http://www.lib.umich.edu/falafel/icons/"
  fa_font_root:
    "http://www.lib.umich.edu/falafel/fonts/"

  fa_width_large: 75em
  fa_width_small: 55em
  fa_width_tiny:  35em

scss_tools_order:
  - scss_tools/utility/**/*.scss
  - scss_tools/style/**/*.scss

scss_rules_order:
  falafel:
    - scss_rules/_reset.scss
    - scss_rules/style/_font.scss
    - scss_rules/style/_text.scss
    - scss_rules/style/_buttons.scss
  falafel_fonts:
    - scss_rules/style/_font.scss
