---
colors:
  um_maize: "#FFCB05"
  um_blue:  "#00274C"

  black: "#000000"
  white: "#FFFFFF"

  grey_1: "#333333"
  grey_2: "#4E4E4E"
  grey_3: "#6E6E6E"
  grey_4: "#CCCCCC"
  grey_5: "#E5E5E5"
  grey_6: "#F2F2F2"
  grey_7: "#FAFAFA"

  main_1: "#00274C"
  main_2: "#0C5292"
  main_3: "#126DC1"
  main_4: "#CCE6FF"
  main_5: "#E6F3FF"
  main_6: "#F2F9FF"

  green_1: "#057C42"
  green_2: "#05A657"
  green_3: "#E2F4EB"

  red_1: "#C53B26"
  red_2: "#ED5D47"
  red_3: "#FFEAE7"

  orange_1: "#AA6500"
  orange_2: "#E77504"
  orange_3: "#FFEEDD"

  teal_1: "#10788E"
  teal_2: "#14A2BF"
  teal_3: "#E4F3F8"

sass_tools_order:
  - sass_tools/utility/**/.scss
  - sass_tools/style/**.scss

sass_variables:
  fa_icon_root: "http://www.lib.umich.edu/falafel/compiled/icons/"
